import { act, cleanup, fireEvent, render, screen } from '@testing-library/react'
import '@testing-library/jest-dom'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { ALL_CONNECTORS } from '../../../src/services/connectors/catalog'
import { Connectors } from './Connectors'
import { useConnectorStore } from '@/stores/connectorStore'
import { en } from '@/i18n/locales/en'
import { zh } from '@/i18n/locales/zh'
import { jp } from '@/i18n/locales/jp'
import { kr } from '@/i18n/locales/kr'
import type { ConnectorDto } from '@/types/connector'
const mocks = vi.hoisted(() => ({ create: vi.fn(), draft: vi.fn(), open: vi.fn(), active: vi.fn(), external: vi.fn(), translations: null as Record<string, string> | null }))
vi.mock('@/i18n', () => ({ useTranslation: () => (key: string) => mocks.translations?.[key] ?? key }))
vi.mock('@/stores/sessionStore', () => ({ useSessionStore: { getState: () => ({ createSession: mocks.create, setActiveSession: mocks.active }) } }))
vi.mock('@/stores/chatStore', () => ({ useChatStore: { getState: () => ({ setComposerDraft: mocks.draft }) } }))
vi.mock('@/stores/tabStore', () => ({ useTabStore: { getState: () => ({ openTab: mocks.open }) } }))
vi.mock('@/lib/desktopHost', () => ({ getDesktopHost: () => ({ shell: { open: mocks.external } }) }))
const item: ConnectorDto = { id: 'feishu', pluginId: 'feishu', packageName: 'feishu-cli', version: '1', homepage: 'https://example.test', credentialMode: 'shared', platforms: ['darwin-arm64'], supported: true, installed: true, enabled: true, connection: 'needs-auth', runtime: 'missing', status: 'needs-auth' }
const refresh = vi.fn(async () => {})
const perform = vi.fn(async () => {})
beforeEach(() => { vi.clearAllMocks(); mocks.translations = null; useConnectorStore.setState({ items: [item], loading: false, error: null, pending: {}, refresh, act: perform }) })
afterEach(() => { cleanup(); vi.useRealTimers() })
describe('Connectors', () => {
  it('explains shared credentials and requires confirmation before account connection', () => {
    render(<Connectors />)
    fireEvent.click(screen.getByRole('button', { name: 'connectors.details' }))
    fireEvent.click(screen.getByRole('button', { name: 'connectors.action.authenticate' }))
    expect(perform).not.toHaveBeenCalled()
    expect(screen.getByRole('dialog')).toHaveTextContent('connectors.shared')
    fireEvent.click(screen.getByRole('button', { name: 'connectors.continue' }))
    expect(perform).toHaveBeenCalledWith('feishu', 'authenticate', { acknowledgeSharedCredentials: true })
  })
  it('polls while operations run and stops on unmount', async () => {
    vi.useFakeTimers()
    useConnectorStore.setState({ items: [{ ...item, operation: { id: 'op', kind: 'authenticate', phase: 'waiting', startedAt: '' } }] })
    const view = render(<Connectors />)
    expect(refresh).toHaveBeenCalledTimes(1)
    await act(async () => { await vi.advanceTimersByTimeAsync(3000) })
    expect(refresh).toHaveBeenCalledTimes(3)
    view.unmount()
    await act(async () => { await vi.advanceTimersByTimeAsync(3000) })
    expect(refresh).toHaveBeenCalledTimes(3)
  })
  it('creates an ordinary task with an unsent draft', async () => {
    useConnectorStore.setState({ items: [{ ...item, status: 'ready', connection: 'connected' }] })
    mocks.create.mockResolvedValue('new-task')
    render(<Connectors />)
    fireEvent.click(screen.getByRole('button', { name: 'connectors.details' }))
    await act(async () => { fireEvent.click(screen.getByRole('button', { name: 'connectors.start' })) })
    expect(mocks.draft).toHaveBeenCalledWith('new-task', { input: 'connectors.feishu.example', attachments: [] })
    expect(mocks.open).toHaveBeenCalledWith('new-task', 'sidebar.newSession')
  })
})

it('keeps local configuration distinct from service readiness and still allows a draft', () => {
  useConnectorStore.setState({ items: [{ ...item, status: 'configured', verification: 'local' }] })
  render(<Connectors />)
  expect(screen.getByText('connectors.status.configured')).toBeInTheDocument()
  expect(screen.queryByText('connectors.status.ready')).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'connectors.details' }))
  expect(screen.getByText('connectors.localVerification')).toBeInTheDocument()
})
it('cancels pending authorization without claiming success or opening unsafe URLs', () => {
  useConnectorStore.setState({ items: [{ ...item, status: 'authorizing', operation: { id: 'op', kind: 'authenticate', startedAt: '', phase: 'waiting', authUrl: 'javascript:alert(1)' } }] })
  render(<Connectors />)
  fireEvent.click(screen.getByRole('button', { name: 'connectors.details' }))
  fireEvent.click(screen.getByRole('button', { name: 'connectors.authorize' }))
  expect(mocks.external).not.toHaveBeenCalled()
  expect(screen.getByRole('alert')).toHaveTextContent('connectors.invalidUrl')
  fireEvent.click(screen.getAllByRole('button', { name: 'common.cancel' }).at(-1)!)
  expect(perform).toHaveBeenCalledWith('feishu', 'cancel')
})
it('filters by added state and keeps a local fallback when a logo cannot load', () => {
  useConnectorStore.setState({ items: [{ ...item, installed: false }] })
  const view = render(<Connectors />)
  fireEvent.error(view.container.querySelector('img')!)
  expect(view.container.querySelector('img')).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'extensions.filter' }))
  fireEvent.click(screen.getByRole('checkbox', { name: 'connectors.added' }))
  expect(screen.queryByText('connectors.feishu.name')).not.toBeInTheDocument()
  expect(screen.getByText('extensions.empty')).toBeInTheDocument()
})

it('shows installed and available versions and labels a connected account without a display name', () => {
  useConnectorStore.setState({ items: [{ ...item, status: 'ready', connection: 'connected', installedVersion: '0.9', version: '1.2', updateAvailable: true }] })
  render(<Connectors />)
  fireEvent.click(screen.getByRole('button', { name: 'connectors.details' }))
  expect(screen.getByRole('button', { name: 'connectors.update' })).toBeInTheDocument()
  expect(screen.getByText('0.9')).toBeInTheDocument()
  expect(screen.getByText('connectors.updateAvailable: 1.2')).toBeInTheDocument()
  expect(screen.getByText('connectors.currentAccount')).toBeInTheDocument()
  expect(screen.queryByText('connectors.noAccount')).not.toBeInTheDocument()
})
it('retains the catalog version for older DTOs without installedVersion', () => {
  render(<Connectors />)
  fireEvent.click(screen.getByRole('button', { name: 'connectors.details' }))
  expect(screen.getByText('1')).toBeInTheDocument()
  expect(screen.getByText('connectors.noAccount')).toBeInTheDocument()
})

it.each(['installing-plugin', 'checking', 'enabling-plugin', 'refreshing-sessions', 'verifying-runtime', 'persistence', 'cancelling'])('shows the concrete %s stage in progress and failures', (phase) => {
  useConnectorStore.setState({ items: [{ ...item, error: 'failed', failedPhase: phase, operation: { id: 'op', kind: 'check', startedAt: '', phase } }] })
  render(<Connectors />)
  fireEvent.click(screen.getByRole('button', { name: 'connectors.details' }))
  expect(screen.getByRole('status')).toHaveTextContent(`connectors.phase.${phase}`)
  expect(screen.getByRole('alert')).toHaveTextContent(`connectors.phase.${phase}`)
})
it.each(['feishu', 'dingtalk', 'wecom'] as const)('shows service-specific account requirements for %s', (id) => {
  useConnectorStore.setState({ items: [{ ...item, id }] })
  render(<Connectors />)
  fireEvent.click(screen.getByRole('button', { name: 'connectors.details' }))
  expect(screen.getByText(`connectors.${id}.requirements`)).toBeInTheDocument()
})

const remote: ConnectorDto = { ...item, id: 'remote-search', displayName: 'Remote Search', description: 'Search project documentation', category: 'search', capabilities: ['Search documents'], transport: 'mcp', credentialMode: 'isolated', setupFields: [{ key: 'apiKey', label: 'API key', secret: true }, { key: 'workspace', label: 'Workspace' }] }
it('filters remote catalog metadata by category and search', () => {
  useConnectorStore.setState({ items: [item, remote] })
  render(<Connectors />)
  fireEvent.click(screen.getByRole('button', { name: 'extensions.filter' }))
  fireEvent.change(screen.getByRole('combobox', { name: 'extensions.categories' }), { target: { value: 'search' } })
  expect(screen.getByRole('button', { name: 'Remote Search' })).toBeInTheDocument()
  expect(screen.queryByRole('button', { name: 'connectors.feishu.name' })).not.toBeInTheDocument()
  fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'absent' } })
  expect(screen.getByText('extensions.empty')).toBeInTheDocument()
})
it('validates partially entered remote configuration and sends it only on the explicit connect action', () => {
  useConnectorStore.setState({ items: [remote] })
  render(<Connectors />)
  fireEvent.click(screen.getByRole('button', { name: 'Remote Search' }))
  expect(screen.getByLabelText('API key')).toHaveAttribute('type', 'password')
  fireEvent.change(screen.getByLabelText('API key'), { target: { value: 'fake-key' } })
  fireEvent.click(screen.getByRole('button', { name: 'connectors.saveAndVerify' }))
  expect(perform).not.toHaveBeenCalled()
  expect(screen.getByLabelText('Workspace')).toHaveAttribute('aria-invalid', 'true')
  expect(screen.getAllByText('connectors.fieldRequired')).toHaveLength(1)
  // A rejected submission reports the missing field, never the entered secret.
  expect(screen.getByRole('dialog')).not.toHaveTextContent('fake-key')
  fireEvent.change(screen.getByLabelText('Workspace'), { target: { value: 'test-space' } })
  fireEvent.click(screen.getByRole('button', { name: 'connectors.saveAndVerify' }))
  expect(perform).toHaveBeenCalledWith('remote-search', 'authenticate', { configuration: { apiKey: 'fake-key', workspace: 'test-space' } })
  expect(screen.getByLabelText('API key')).toHaveValue('')
})
it('requires every setup field before connecting a connector that has no stored credential', () => {
  useConnectorStore.setState({ items: [remote] })
  render(<Connectors />)
  fireEvent.click(screen.getByRole('button', { name: 'Remote Search' }))
  fireEvent.click(screen.getByRole('button', { name: 'connectors.connectService' }))
  expect(perform).not.toHaveBeenCalled()
  expect(screen.getByLabelText('API key')).toHaveAttribute('aria-invalid', 'true')
  expect(screen.getByLabelText('Workspace')).toHaveAttribute('aria-invalid', 'true')
  expect(screen.getAllByText('connectors.fieldRequired')).toHaveLength(2)
})
it('does not erase stored credentials when a verified connector is connected with an untouched form', () => {
  useConnectorStore.setState({ items: [{ ...remote, status: 'error', failedPhase: 'authorizing', connection: 'connected', verification: 'remote' }] })
  render(<Connectors />)
  fireEvent.click(screen.getByRole('button', { name: 'Remote Search' }))
  fireEvent.click(screen.getByRole('button', { name: 'connectors.connectService' }))
  expect(perform).toHaveBeenCalledWith('remote-search', 'authenticate', {})
})
it('still requires every setup field when a stored credential is being replaced', () => {
  useConnectorStore.setState({ items: [{ ...remote, status: 'error', failedPhase: 'authorizing', connection: 'connected', verification: 'remote' }] })
  render(<Connectors />)
  fireEvent.click(screen.getByRole('button', { name: 'Remote Search' }))
  fireEvent.change(screen.getByLabelText('API key'), { target: { value: 'rotated-key' } })
  fireEvent.click(screen.getByRole('button', { name: 'connectors.saveAndVerify' }))
  expect(perform).not.toHaveBeenCalled()
  expect(screen.getByLabelText('Workspace')).toHaveAttribute('aria-invalid', 'true')
})
it('opens configuration details from the row action without automatically sending credentials', () => {
  useConnectorStore.setState({ items: [{ ...remote, installed: false, status: 'not-installed' }] })
  render(<Connectors />)
  fireEvent.click(screen.getByRole('button', { name: 'connectors.details' }))
  expect(screen.getByRole('dialog')).toBeInTheDocument()
  expect(perform).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'connectors.action.prepare' }))
  expect(perform).toHaveBeenCalledWith('remote-search', 'prepare', {})
})
it('opens details from the row action without installing a connector that needs no configuration', () => {
  const plain: ConnectorDto = { ...remote, id: 'plain-service', displayName: 'Plain Service', setupFields: undefined }
  useConnectorStore.setState({ items: [{ ...plain, installed: false, status: 'not-installed' }] })
  render(<Connectors />)
  fireEvent.click(screen.getByRole('button', { name: 'connectors.details' }))
  expect(screen.getByRole('dialog')).toBeInTheDocument()
  expect(perform).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'connectors.action.prepare' }))
  expect(perform).toHaveBeenCalledWith('plain-service', 'prepare', {})
})
it('renders a stable skeleton instead of empty catalog while loading', () => {
  useConnectorStore.setState({ items: [], loading: true })
  render(<Connectors />)
  expect(screen.getByRole('status', { name: 'connectors.loading' })).toBeInTheDocument()
  expect(screen.queryByText('extensions.empty')).not.toBeInTheDocument()
})

it('switches remote catalog copy and draft examples with the UI language without leaking Chinese metadata', async () => {
  const localized = { ...remote, id: 'amap', displayName: zh['connectors.amap.name'], description: zh['connectors.amap.description'], requirements: zh['connectors.amap.requirements'], example: zh['connectors.amap.example'], capabilities: [zh['connectors.amap.description']], status: 'ready' as const, connection: 'connected' as const }
  useConnectorStore.setState({ items: [localized] })
  mocks.translations = en
  const view = render(<Connectors />)
  expect(screen.getByText(en['connectors.amap.description'])).toBeInTheDocument()
  expect(screen.queryByText(zh['connectors.amap.description'])).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: en['connectors.amap.name'] }))
  expect(screen.getByText(en['connectors.amap.requirements'])).toBeInTheDocument()
  expect(screen.getByText(en['connectors.officialMcp'])).toBeInTheDocument()
  expect(screen.queryByText(en['connectors.capabilities'])).not.toBeInTheDocument()
  mocks.translations = jp
  view.rerender(<Connectors />)
  expect(screen.getByText(jp['connectors.amap.requirements'])).toBeInTheDocument()
  expect(screen.queryByText(en['connectors.amap.requirements'])).not.toBeInTheDocument()
  mocks.translations = kr
  view.rerender(<Connectors />)
  expect(screen.getByText(kr['connectors.amap.requirements'])).toBeInTheDocument()
  mocks.create.mockResolvedValue('translated-draft')
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: kr['connectors.start'] })) })
  expect(mocks.draft).toHaveBeenCalledWith('translated-draft', { input: kr['connectors.amap.example'], attachments: [] })
})

it.each(['ready', 'disabled', 'error'] as const)('rotates configured credentials from %s by authenticating rather than checking stale settings', (status) => {
  useConnectorStore.setState({ items: [{ ...remote, status, connection: 'connected', failedPhase: status === 'error' ? 'checking' : undefined }] })
  render(<Connectors />)
  fireEvent.click(screen.getByRole('button', { name: 'Remote Search' }))
  expect(screen.getByRole('button', { name: 'connectors.saveAndVerify' })).toBeDisabled()
  fireEvent.change(screen.getByLabelText('API key'), { target: { value: 'rotated-key' } })
  fireEvent.change(screen.getByLabelText('Workspace'), { target: { value: 'workspace' } })
  fireEvent.click(screen.getByRole('button', { name: 'connectors.saveAndVerify' }))
  expect(perform).toHaveBeenCalledWith('remote-search', 'authenticate', { configuration: { apiKey: 'rotated-key', workspace: 'workspace' } })
})
it('labels remote authorization as a service connection while retaining account wording for native connectors', () => {
  useConnectorStore.setState({ items: [remote, item] })
  render(<Connectors />)
  expect(screen.getByText('connectors.needsService')).toBeInTheDocument()
  expect(screen.getByText('connectors.status.needs-auth')).toBeInTheDocument()
})

it('separates tools from services and filters domestic and global services without hiding native legacy DTOs', () => {
  const tool = { ...item, id: 'test-skill', displayName: 'Test skill', collection: 'tools' as const, transport: 'skills' as const, region: 'global' as const }
  useConnectorStore.setState({ items: [item, { ...remote, region: 'global' }, tool] })
  const view = render(<Connectors />)
  expect(screen.queryByRole('button', { name: 'Test skill' })).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'extensions.filter' }))
  fireEvent.change(screen.getByRole('combobox', { name: 'connectors.region' }), { target: { value: 'china' } })
  expect(screen.getByRole('button', { name: 'connectors.feishu.name' })).toBeInTheDocument()
  expect(screen.queryByRole('button', { name: 'Remote Search' })).not.toBeInTheDocument()
  fireEvent.change(screen.getByRole('combobox', { name: 'connectors.region' }), { target: { value: 'global' } })
  expect(screen.queryByRole('button', { name: 'connectors.feishu.name' })).not.toBeInTheDocument()
  expect(screen.getByRole('button', { name: 'Remote Search' })).toBeInTheDocument()
  view.rerender(<Connectors mode="skills" />)
  expect(screen.getByRole('button', { name: 'Test skill' })).toBeInTheDocument()
  expect(screen.queryByRole('combobox', { name: 'connectors.region' })).not.toBeInTheDocument()
  expect(screen.queryByRole('button', { name: 'Remote Search' })).not.toBeInTheDocument()
})
it('describes installed skill bundles without account or runtime readiness claims and checks without credential consent', () => {
  useConnectorStore.setState({ items: [{ ...item, id: 'test-skill', displayName: 'Test skill', collection: 'tools', transport: 'skills', setupFields: [{ key: 'bad', label: 'Should not appear' }] }] })
  render(<Connectors mode="skills" />)
  fireEvent.click(screen.getByRole('button', { name: 'Test skill' }))
  expect(screen.getByRole('dialog')).toHaveTextContent('connectors.skillsPending')
  expect(screen.getByText('connectors.skillsRuntimeInfo')).toBeInTheDocument()
  expect(screen.queryByText('connectors.account')).not.toBeInTheDocument()
  expect(screen.queryByText('connectors.shared')).not.toBeInTheDocument()
  expect(screen.queryByLabelText('Should not appear')).not.toBeInTheDocument()
  expect(screen.queryByRole('button', { name: 'connectors.action.authenticate' })).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'connectors.verifySkills' }))
  expect(perform).toHaveBeenCalledWith('test-skill', 'check', {})
})
it('shows loaded skills and prepares an unsent ordinary task for tool plugins', async () => {
  useConnectorStore.setState({ items: [{ ...item, id: 'test-skill', displayName: 'Test skill', example: 'Use this skill', collection: 'tools', transport: 'skills', status: 'configured', enabled: true }] })
  mocks.create.mockResolvedValue('skill-task')
  render(<Connectors mode="skills" />)
  expect(screen.getByText('connectors.skillsLoaded')).toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'Test skill' }))
  expect(screen.queryByText('connectors.localVerification')).not.toBeInTheDocument()
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: 'connectors.start' })) })
  expect(mocks.draft).toHaveBeenCalledWith('skill-task', { input: 'Use this skill', attachments: [] })
})

it('renders Remotion in the plugin catalog without duplicating it among pure skills', () => {
  useConnectorStore.setState({ items: ALL_CONNECTORS.map(definition => ({ ...definition, supported: true, installed: false, enabled: false, connection: 'disconnected', runtime: 'missing', status: 'not-installed' })) })
  const view = render(<Connectors />)
  const rows = () => view.container.querySelectorAll('img').length
  expect(rows()).toBe(50)
  expect(screen.getByRole('button', { name: 'Remotion' })).toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'extensions.filter' }))
  fireEvent.change(screen.getByRole('combobox', { name: 'connectors.region' }), { target: { value: 'china' } })
  expect(rows()).toBe(22)
  fireEvent.change(screen.getByRole('combobox', { name: 'connectors.region' }), { target: { value: 'global' } })
  expect(rows()).toBe(24)
  view.rerender(<Connectors mode="skills" />)
  expect(rows()).toBe(5)
  expect(screen.queryByRole('button', { name: 'Remotion' })).not.toBeInTheDocument()
  for (const category of ['development', 'design']) expect(screen.getByRole('option', { name: `connectors.category.${category}` })).toBeInTheDocument()
  for (const category of ['office', 'search', 'maps', 'data', 'finance', 'legal', 'productivity']) expect(screen.queryByRole('option', { name: `connectors.category.${category}` })).not.toBeInTheDocument()
})

it('uses plugin language for the mixed market and omits redundant connector badges on service rows', () => {
  render(<Connectors />)
  expect(screen.getByRole('searchbox', { name: 'extensions.searchPlugins' })).toHaveAttribute('placeholder', 'extensions.searchPlugins')
  expect(screen.queryByText('extensions.pluginsSubtitle')).not.toBeInTheDocument()
  expect(screen.getByRole('button', { name: 'extensions.filter' })).toHaveAttribute('aria-expanded', 'false')
  expect(screen.queryByRole('radiogroup')).not.toBeInTheDocument()
  expect(screen.queryByRole('combobox')).not.toBeInTheDocument()
  expect(screen.queryByRole('checkbox')).not.toBeInTheDocument()
  expect(screen.queryByText('connectors.kind')).not.toBeInTheDocument()
  expect(screen.queryByText('connectors.subtitle')).not.toBeInTheDocument()
})

it('uses the shared skill query and installed filter without presenting a second search or filter bar', () => {
  const skill = { ...item, id: 'test-skill', displayName: 'Selected skill', description: 'Create diagrams', collection: 'tools' as const, transport: 'skills' as const }
  useConnectorStore.setState({ items: [skill, { ...skill, id: 'another-skill', displayName: 'Another skill', description: 'Write code', installed: false }] })
  const view = render(<Connectors mode="skills" embedded externalQuery="diagrams" />)
  expect(screen.getByRole('button', { name: 'Selected skill' })).toBeInTheDocument()
  expect(screen.queryByRole('button', { name: 'Another skill' })).not.toBeInTheDocument()
  expect(screen.queryByRole('searchbox')).not.toBeInTheDocument()
  expect(screen.queryByRole('radiogroup')).not.toBeInTheDocument()
  expect(screen.queryByText('connectors.toolKind')).not.toBeInTheDocument()
  view.rerender(<Connectors mode="skills" embedded externalQuery="" installedFilter="installable" />)
  expect(screen.queryByRole('button', { name: 'Selected skill' })).not.toBeInTheDocument()
  expect(screen.getByRole('button', { name: 'Another skill' })).toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'Another skill' }))
  expect(screen.getByRole('dialog')).toHaveTextContent('extensions.skills')
  expect(screen.getByRole('dialog')).not.toHaveTextContent('connectors.toolKind')
})

it('combines added state, region, category and search in the filter panel, restores focus on Escape, and resets only filters', () => {
  useConnectorStore.setState({ items: [item, { ...remote, region: 'global', installed: true }, { ...remote, id: 'uninstalled-search', displayName: 'Uninstalled Search', region: 'global', installed: false }] })
  render(<Connectors />)
  const trigger = screen.getByRole('button', { name: 'extensions.filter' })
  expect(screen.queryByRole('region', { name: 'extensions.filter' })).not.toBeInTheDocument()
  fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'Search' } })
  fireEvent.click(trigger)
  expect(trigger).toHaveAttribute('aria-expanded', 'true')
  fireEvent.click(screen.getByRole('checkbox', { name: 'connectors.added' }))
  fireEvent.change(screen.getByRole('combobox', { name: 'connectors.region' }), { target: { value: 'global' } })
  const category = screen.getByRole('combobox', { name: 'extensions.categories' })
  fireEvent.change(category, { target: { value: 'search' } })
  expect(screen.getByRole('button', { name: 'Remote Search' })).toBeInTheDocument()
  expect(screen.queryByRole('button', { name: 'Uninstalled Search' })).not.toBeInTheDocument()
  expect(screen.queryByRole('button', { name: 'connectors.feishu.name' })).not.toBeInTheDocument()
  expect(trigger).toHaveTextContent('3')
  category.focus()
  fireEvent.keyDown(category, { key: 'Escape' })
  expect(screen.queryByRole('region', { name: 'extensions.filter' })).not.toBeInTheDocument()
  expect(trigger).toHaveFocus()
  expect(trigger).toHaveAttribute('aria-expanded', 'false')
  fireEvent.click(trigger)
  expect(screen.getByRole('checkbox', { name: 'connectors.added' })).toBeChecked()
  fireEvent.click(screen.getByRole('button', { name: 'connectors.resetFilters' }))
  expect(screen.getByRole('checkbox', { name: 'connectors.added' })).not.toBeChecked()
  expect(screen.getByRole('combobox', { name: 'connectors.region' })).toHaveValue('all')
  expect(screen.getByRole('combobox', { name: 'extensions.categories' })).toHaveValue('all')
  expect(screen.getByRole('searchbox')).toHaveValue('Search')
  expect(screen.getByRole('button', { name: 'Uninstalled Search' })).toBeInTheDocument()
  expect(trigger).not.toHaveTextContent('3')
})

it('manages all installed packages including pure skills without market filters or uninstalled entries', () => {
  const skill = { ...item, id: 'test-skill', displayName: 'Managed skill', collection: 'tools' as const, transport: 'skills' as const }
  useConnectorStore.setState({ items: [item, skill, { ...remote, installed: false }] })
  render(<Connectors management />)
  expect(screen.getByRole('button', { name: 'connectors.feishu.name' })).toBeInTheDocument()
  expect(screen.getByRole('button', { name: 'Managed skill' })).toBeInTheDocument()
  expect(screen.queryByRole('button', { name: 'Remote Search' })).not.toBeInTheDocument()
  expect(screen.getAllByRole('button', { name: 'market.uninstall.action' })).toHaveLength(2)
  expect(screen.queryByRole('button', { name: 'extensions.filter' })).not.toBeInTheDocument()
  fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'Managed skill' } })
  expect(screen.queryByRole('button', { name: 'connectors.feishu.name' })).not.toBeInTheDocument()
  expect(screen.getByRole('button', { name: 'Managed skill' })).toBeInTheDocument()
})

it('confirms management removal, allows cancellation and keeps unsupported installed packages removable', () => {
  useConnectorStore.setState({ items: [{ ...item, supported: false }] })
  render(<Connectors management />)
  fireEvent.click(screen.getByRole('button', { name: 'market.uninstall.action' }))
  expect(screen.getByRole('dialog')).toHaveTextContent('connectors.removeInfo')
  expect(perform).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'common.cancel' }))
  expect(perform).not.toHaveBeenCalled()
  expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'market.uninstall.action' }))
  fireEvent.click(screen.getByRole('button', { name: 'connectors.continue' }))
  expect(perform).toHaveBeenCalledWith('feishu', 'remove', { acknowledgeSharedCredentials: true })
})

it('keeps active installs visible for cancellation and protects pending removals from duplicate clicks', () => {
  useConnectorStore.setState({ items: [{ ...remote, installed: false, operation: { id: 'op', kind: 'prepare', phase: 'downloading', startedAt: '' } }, item], pending: { feishu: true } })
  render(<Connectors management />)
  expect(screen.getByRole('button', { name: 'Remote Search' })).toBeInTheDocument()
  expect(screen.getByRole('button', { name: 'market.uninstall.action' })).toBeDisabled()
  fireEvent.click(screen.getByRole('button', { name: 'Remote Search' }))
  fireEvent.click(screen.getByRole('button', { name: 'common.cancel' }))
  expect(perform).toHaveBeenCalledWith('remote-search', 'cancel')
})

it('keeps an empty management list scoped to installed packages without a market reset', () => {
  useConnectorStore.setState({ items: [{ ...item, installed: false }] })
  render(<Connectors management />)
  expect(screen.getByText('connectors.emptyAdded')).toBeInTheDocument()
  expect(screen.queryByRole('button', { name: 'connectors.resetFilters' })).not.toBeInTheDocument()
})

it('distinguishes a management search miss from having no installed packages', () => {
  render(<Connectors management />)
  fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'missing-service' } })
  expect(screen.getByText('connectors.emptySearch')).toBeInTheDocument()
  expect(screen.queryByText('connectors.emptyAdded')).not.toBeInTheDocument()
})
